Repository ClickPickProject/FrontEnd, pull requests merged in 2024-03, with the labels that each got.

#17 게시글 상세 페이지 구현
  package.json
  src/app/content/center/page.jsx
  src/app/content/community/[id]/page.jsx
  src/app/content/community/page.jsx
  src/app/content/community/write/page.jsx
  src/app/content/layout.jsx
  src/app/content/notice/page.jsx
  src/app/content/page.jsx
  src/app/content/place/page.jsx
  src/app/content/profile/page.jsx
  src/app/layout.jsx
  src/atoms/editorContentState.jsx
  src/components/Community/BestPost/StatusView.jsx
  src/components/Community/BestPost/WriterView.jsx
  src/components/Community/Hashtag.jsx
  src/components/Community/HashtagView.jsx
  src/components/Community/PostDetail.jsx
  src/components/Community/PostList.jsx
  src/components/CustomEditor.jsx
  src/components/RecoilRootWrapper.jsx
  src/json/db.json
  src/json/member.json
  yarn.lock
Labels: 기능, 디자인

#18 Feat/post 일부 스타일 조정
  src/app/content/community/[id]/page.jsx
  src/app/content/community/write/page.jsx
  src/atoms/PostState.jsx
  src/atoms/editorContentState.jsx
  src/components/Community/BestPost/WriterView.jsx
  src/components/Community/PostDetail.jsx
  src/components/Community/PostList.jsx
  src/json/db.json
Labels: 디자인

#19 MSW 라이브러리 추가 작업 (실험적)
  package.json
  public/mockServiceWorker.js
  src/app/content/community/write/page.jsx
  src/app/layout.jsx
  src/atoms/PostState.jsx
  src/components/Community/PostDetail.jsx
  src/components/Community/PostList.jsx
  src/mocks/MSWComponent.jsx
  src/mocks/browser.js
  src/mocks/handlers.js
  src/mocks/index.js
  src/mocks/server.js
  yarn.lock
Labels: 기능

#25 [login] logic구현
  .env.production
  next.config.js
  package.json
  src/app/content/center/page.jsx
  src/app/content/community/[id]/page.jsx
  src/app/content/community/page.jsx
  src/app/content/community/write/page.jsx
  src/app/content/layout.jsx
  src/app/content/notice/page.jsx
  src/app/layout.jsx
  src/app/login/page.jsx
  src/app/signup/page.jsx
  src/atoms/PostState.jsx
  src/atoms/editorContentState.jsx
  src/atoms/tokenState.jsx
  src/components/Community/BestPost/StatusView.jsx
  src/components/Community/BestPost/WriterView.jsx
  src/components/Community/BestPost/index.jsx
  src/components/Community/Comment.jsx
  src/components/Community/CommentWrite.jsx
  src/components/Community/Comments.jsx
  src/components/Community/HashtagView.jsx
  src/components/Community/PostDetail.jsx
  src/components/Community/PostList.jsx
  src/components/Community/ReplyComments.jsx
  src/components/Community/SideNavbar.jsx
  src/components/Home/HomeFirstSection.jsx
  src/components/Home/HomeNavbar.jsx
  src/components/Loading.jsx
  src/components/NoticePostList.jsx
  src/components/ReactQueryClientProvider.jsx
  src/components/Search.jsx
  src/components/UI/Icons/CallIcon.jsx
  src/components/UI/Icons/CommentIcon.jsx
  src/components/UI/Icons/EmptyHeartIcon.jsx
  src/components/UI/Icons/FillHeartIcon.jsx
  src/components/UI/Icons/LetterIcon.jsx
  src/components/UI/Icons/ReplyIcon.jsx
  src/components/UI/Icons/ReportIcon.jsx
  src/components/UI/Icons/index.jsx
  src/components/context/AuthContext.jsx
  src/json/db.json
  src/mocks/handlers.js
  yarn.lock
Labels: 기능

#15 [마이프로필 구현]
  next.config.js
  src/app/content/layout.jsx
  src/app/content/profile/page.jsx
  src/atoms/userInfoState.jsx
  src/components/Profile/LikeComment.jsx
  src/components/Profile/LikePost.jsx
  src/components/Profile/MyCommentList.jsx
  src/components/Profile/MyPostList.jsx
  src/components/Profile/MyProfile.jsx
Labels: 디자인
